//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Url_Shortener_DatabaseExercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_id { get; set; }
        public string short_url { get; set; }
        public System.DateTime time_date { get; set; }
        public string ip_address { get; set; }
    }
}
